<a href="https://colab.research.google.com/github/varunptel/NumPy_pilot/blob/main/advance_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# RANDOM NUMBERS IN NUMPY

There are no true numbers in computer language as everything is just a set of instruction. So the random numbers generated by NumPy is just a deterministic algorithms. Therefore they are called pseudo-random numbers.

NumPy has built-in module numpy.random which is fast, vectorized and supports a lot of probability distributions.


## Generate Random Numbers:

In [5]:
from numpy import random

x = random.randint(5) #integers
y = random.rand()   #random float

print(x)
print(y)

0
0.028053169279874002


In [12]:
# Generate random array

x = random.randint(50, size = (5)) #Integers 1-D. Change the size to (a,b) for 2D and so on.
y = random.rand(5) #1D float number random numbers array. (a,b) for 2D and so one.

print(x)
print(y)

[ 0  8 18 29 28]
[0.71949368 0.9859745  0.67971794 0.2943545  0.74596475]


In [15]:
# To choose a random value from the array we can use choice() function from the random functions.

x = random.choice([35,69,45,55,56,78,3,55,2,66,0])

y = random.choice([35,69,45,55,56,78,3,55,2,66,0], size = (3,5)) #returns the array of size 3*5 from the array
print(x)
print(y)

2
[[35 69 56 45 35]
 [78 78  0  0 45]
 [66  3  0 35 56]]


### Modern Generator vs the Legacy interface

There are number of reason to switch from the legacy interface (the old np.random.rand(), np.random.randn(), np.random.seed(), etc) to modern generator(np.random.default_rng()):

1. It is Faster:
It uses modern, high-performance bit generator by default.

2. More flexible
- The Generator gives you way more control and features that the old API simply doesn’t have:

- You can pick the exact algorithm you want.

- Many more distributions and advanced sampling methods (e.g., multivariate_normal, hypergeometric, lognormal, etc.) that are either missing or less convenient in the legacy API.

In [16]:
# Comparison between old and new random generators.
import numpy as np
import timeit

rng = np.random.default_rng()          # modern
legacy = np.random                    # old

# Generate 10 million standard normal numbers
print("Modern Generator:", timeit.timeit(lambda: rng.standard_normal(10_000_000), number=3))
print("Legacy np.random :", timeit.timeit(lambda: legacy.randn(10_000_000), number=3))

Modern Generator: 0.8733992649999891
Legacy np.random : 0.9236056590000317
