<a href="https://colab.research.google.com/github/varunptel/NumPy_pilot/blob/main/Learning_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learning NumPy in Jupyter Notebook.


---



NumPy is an open source library which is widely used in Science and engineering.It contains multidimensional array data structures, such as the homogeneous, N-dimensional "ndarray".

Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

Depending on the characteristics of the data and the types of operations that need to be performed, other containers may be more appropriate; by exploiting these characteristics, we can improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks. NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

In [ ]:
# creating an numpy ndarray using array function

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(type(arr)) #type function is used to get the type of an input object
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [ ]:
# Dimensions in Arrays
a = np.array(0)   # 0-D array
b = np.array([1,2,3])   #1-D array
c = np.array([[1,2,3],[4,5,6]])   #2-D array
d = np.array([[[1,2,3,4],[0,0,0,0]],[[1,2,3,4],[4,5,6,7]]])  # 3D Array

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
''' An array can have any number of dimensions.
When an array is created, you can define the number of dimensions by using the ndmin argument '''
arr = np.array([1,2,3,4], ndmin = 2)
print(arr)
print(f"Number of Dimensions: {arr.ndim}")

[[1 2 3 4]]
Number of Dimensions: 2


# Access Array Elements



In [ ]:
''' Array indexing is almost similar to that of lists.
The indexes in NumPy starts with 0.'''
# Access 1-D Arrays.
import numpy as np

arr = np.array([1,2,3,4])

print(arr[0])
print(arr[1])

1
2


In [ ]:
# Access 2-D Arrays.

arr= np.array([[1,2,3],[4,5,6]])

print(arr[0, 2])  #Refers to the 3rd element in the 1st Row
print(arr[1,0])   # Refers to the 1st element in 2nd row


3
4


In [ ]:
# Accessing 3-D Array.

arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
'''[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]   First element is the outermost layer of the tensor. Second and third elements are the part of the inner matrix.'''

print(arr3d[1,0,0])  #1st
print(arr3d[1,1,0])  #2nd
print(arr3d[0,1,2])  #3rd

7
10
6


In [ ]:
# Negative Indexing
arr = np.array([1,2,3])

print(arr[-1])

print(arr[-2])

print(arr[-3])

3
2
1


# Slicing Arrays.

In [ ]:
'''
Slicing in python means taking elements from one given index to another given index.
General syntax: [start:end:step].
If no start index is mentioned then it is considered 0.
If no end index is mentioned then it is the length of array in that dimension.
If we don't pass step its considered 1.'''
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[0:3])

print(arr[2:])

print(arr[-3:-1])  # Negative Index slicing

print(arr[0:4:2])  # Steps included

print(arr[::3])

[1 2 3]
[3 4 5]
[3 4]
[1 3]
[1 4]


In [ ]:
# Slicing 2-D array
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1, 1:4]) # From One index

print(arr)



'''
Explanation:
1) the part 0:2 refers to rows. It selects rows starting from index 0 up to index 2(2 is not included).
2) the part 2 refers to columns. For each of the selected rows, it picks the element at column index 2.'''

print(arr[0:2, 2])



''' Explanation:
1) the part 0:2 refers to rows. It selects rows starting from index 0 up to index 2(2 is not included).
2) the part 0:2 refers to columns. For each of the selected rows, it picks the element at columns up to index 2.'''
print(arr[0:2, 0:2])


[7 8 9]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[3 8]
[[1 2]
 [6 7]]


# Data Types in NumPy

Since the NumPy can only process homogeneous data, no two type of data type can be included simultaneously.

By default there mainly 5 data types in Python such as string, integer, float, boolean and complex.

Whereas NumPy has some extra data types and can be referred by the characters as follows:

| Type Code | Data Type | Description |
| :--- | :--- | :--- |
| `'?'`, `'b1'` | **Boolean** | Standard True/False |
| `'b'` | **(Signed) Byte** | Signed 8-bit integer |
| `'B'` | **Unsigned Byte** | Unsigned 8-bit integer |
| `'i'` | **(Signed) Integer** | (signed) integer |
| `'u'` | **Unsigned Integer** | unsigned integer |
| `'f'` | **Floating-point** | floating-point |
| `'c'` | **Complex-floating point** | complex-floating point |
| `'m'` | **Timedelta** | timedelta |
| `'M'` | **Datetime** | datetime |
| `'O'` | **(Python) Objects** | (Python) objects |
| `'S'`, `'a'` | **Zero-terminated bytes** | zero-terminated bytes (not recommended) |
| `'U'` | **Unicode string** | Unicode string |
| `'V'` | **Raw data (void)** | raw data (void) |


Source: https://numpy.org/doc/stable/reference/arrays.dtypes.html#arrays-dtypes


In [ ]:
import numpy as np

string_array = np.array(['apple', 'banana', 'cherry'])

integer_array = np.array([1,2,3,4])

print(string_array.dtype)

print(integer_array.dtype)

<U6
int64


In [ ]:
''' Creating arrays with a defined Data types.
we can take optional argument "dtype" inside the array function to create a defined data types.
'''
import numpy as np

arr = np.array([1,2,3,4], dtype='S')

print(arr.dtype)   # For i, u, f, S and U we can define size as well.

arr = np.array([11,22,43,64], dtype='S4')
print(arr.dtype)

|S1
|S4


In [ ]:
# If a type is given in which elements can't be casted then NumPy will raise a ValueError.

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [12]:
# Converting Data type on an Existing arrays.
''' The most efficient way to change the data type is by copying the array with using astype() method.
It allows us to create a copy of the array and allow us to specify the new data type.
'''
arr = np.array([1.1, 3.2, 4.9])

new_arr = arr.astype('i')

print(arr.dtype)

print(new_arr.dtype)

float64
int32


In [1]:
''' NumPy Copy vs View of Arrays:
Copy: New Array, Owns the Data, Changes to copy will not change the original array and vice versa.
View: Just Original Array, Doesn't own the data, changes made to copy will change the original array and vice versa.
'''
# Copy
import numpy as np

arr = np.array([1,2,3,4,5])
new_arr = arr.copy()
arr[0] = 10

print(arr)
print(new_arr)



[10  2  3  4  5]
[1 2 3 4 5]


In [6]:
# View:
arr = np.array([1,2,3,4,5])
new_arr = arr.view()
arr[0] = 10  # Change made to the original
print(arr)
print(new_arr)

new_arr[1] = 40  #Change made to the view function
print(arr)
print(new_arr)   #To check if the copy or view owns a data or not, then use base attribute.

print(new_arr.base) # It will return the none if it owns the data and it will return the original array if it doesn't own the data.

[10  2  3  4  5]
[10  2  3  4  5]
[10 40  3  4  5]
[10 40  3  4  5]
[10 40  3  4  5]


## Shape of an Array

It tells the number of elements in each dimension.
It has an attribute called shape that returns the tuple with each index having number of elements in it.

---

## Reshaping of an Array

It helps to change the shape of any array.
We can add or remove the number of elements in each dimension by reshaping.
The reshaping can be possible only when the number of elements are equal in both the shapes.

---
## Unknown Dimension:
One unknown dimension is allowed to use. Numpy will automatically calculate the number for you using -1 as the value.

---
# Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.
We can use reshape(-1) to do this.